### ISSUE TITLE
Call to undefined method CoCart_Session_Handler::has_session()

### ISSUE THREAD

**Issue by guntercn** [co-cart/co-cart#120]
Hi 
there is an error when you start the product selection screen

plugins
CoCart 2.1.2
WooCommerce 4.2.0
WooCommerce Stripe Gateway 4.4.0
WooCommerce PayPal Checkout Gateway 2.0.2

example 
http://YOUR_SITE/product/YOUR_PRODUCT NAME

```php
2020-06-06T18:09:28+00:00 CRITICAL Uncaught Error: Call to undefined method CoCart_Session_Handler::has_session() in /home/USERNAME/public_html/WEB_FOLDER/wp-content/plugins/woocommerce-gateway-stripe/includes/payment-methods/class-wc-stripe-payment-request.php:150
Stack trace: #0 /home/USERNAME/public_html/WEB_FOLDER/wp-includes/class-wp-hook.php(287): WC_Stripe_Payment_Request->set_session('') #1 /home/USERNAME/public_html/WEB_FOLDER/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array) #2 /home/USERNAME/public_html/WEB_FOLDER/wp-includes/plugin.php(478): WP_Hook->do_action(Array) #3 /home/USERNAME/public_html/WEB_FOLDER/wp-includes/template-loader.php(13): do_action('template_redire...') #4 /home/USERNAME/public_html/WEB_FOLDER/wp-blog-header.php(19): require_once('/home/USERNAME...') #5 /home/USERNAME/public_html/WEB_FOLDER/index.php(17): require('/home/USERNAME...') #6 {main}
  thrown en /home/USERNAME/public_html/WEB_FOLDER/wp-content/plugins/woocommerce-gateway-stripe/includes/payment-methods/class-wc-stripe-payment-request.php en la línea 150
```

thanks.

**Comment by seb86** [comment]
Thank you for reporting the error @guntercn 

Looking into it now.

**Comment by seb86** [comment]
It appears to be caused when **Payment Request Buttons** is enabled in Stripe Gateway settings @guntercn 

Can you disable it for now until I find a work around please.

Thank you.

**Comment by seb86** [comment]
Fixed. Pushing update now @guntercn
