### ISSUE TITLE
Compatibility with WP-GraphQL

### ISSUE THREAD

**Issue by vince93290** [co-cart/co-cart#229]
I am currently developing an ecommerce with front (next js) for static product page  and back (wordpress) technology, I use wpgraphql, wp-graphql-woocommerce and cocart as a plug-in.

I have no problem when I use cocart v2 everything works but when I make the update to version 3 wpgraphql no longer works.

plugin version:
wpgraphql: 1.3.5
WPGraphQL WooCommerce (WooGraphQL): 0.8.1
Cocart v3 3.0.0-beta.4

![cocart bug](https://user-images.githubusercontent.com/44445302/116698471-b7f67a80-a9c4-11eb-952e-242d81cef254.png)

**Comment by seb86** [comment]
@vince93290 Could update to CoCart RC 1? There was an authentication issue in beta 4 that could be related to your problem. If you have any other error logs that could also identify where the problem is located that would be helpful.

Thank you for your report.

**Comment by vince93290** [comment]
> @vince93290 Could update to CoCart RC 1? There was an authentication issue in beta 4 that could be related to your problem. If you have any other error logs that could also identify where the problem is located that would be helpful.
> 
> Thank you for your report.

I updated to the realesed candidate and I still have the same error.

**Comment by seb86** [comment]
Any error logs? I assume you have debug mode enabled, right?

**Comment by vince93290** [comment]
if I deactivate graphql woocommerce plugin, wpgraphql plugin works with cocart plugin

**Comment by vince93290** [comment]
> Any error logs? I assume you have debug mode enabled, right?

sorry i am not very familiar with php and wordpress development.

how can i activate debug mode?

**Comment by seb86** [comment]
[This guide](https://wpforms.com/developers/how-to-enable-debugging-in-wordpress/) is pretty straight forward.

**Comment by vince93290** [comment]
> [This guide](https://wpforms.com/developers/how-to-enable-debugging-in-wordpress/) is pretty straight forward.

ok know it is activate where i can see debug log ?

**Comment by vince93290** [comment]
`[30-Apr-2021 14:40:13 UTC] PHP Notice:  ob_end_flush(): failed to send buffer of zlib output compression (1) in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/functions.php on line 4757
[30-Apr-2021 14:40:13 UTC] PHP Notice:  ob_end_flush(): failed to send buffer of zlib output compression (1) in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/functions.php on line 4757
[30-Apr-2021 14:40:15 UTC] PHP Notice:  ob_end_flush(): failed to send buffer of zlib output compression (1) in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/functions.php on line 4757
[30-Apr-2021 14:40:15 UTC] PHP Notice:  ob_end_flush(): failed to send buffer of zlib output compression (1) in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/functions.php on line 4757
[30-Apr-2021 14:40:19 UTC] PHP Notice:  ob_end_flush(): failed to send buffer of zlib output compression (1) in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/functions.php on line 4757
[30-Apr-2021 14:40:19 UTC] PHP Notice:  ob_end_flush(): failed to send buffer of zlib output compression (1) in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/functions.php on line 4757
[30-Apr-2021 14:40:27 UTC] PHP Notice:  ob_end_flush(): failed to send buffer of zlib output compression (1) in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/functions.php on line 4757
[30-Apr-2021 14:40:27 UTC] PHP Notice:  ob_end_flush(): failed to send buffer of zlib output compression (1) in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/functions.php on line 4757
[30-Apr-2021 14:40:30 UTC] PHP Notice:  ob_end_flush(): failed to send buffer of zlib output compression (1) in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/functions.php on line 4757
[30-Apr-2021 14:40:30 UTC] PHP Notice:  ob_end_flush(): failed to send buffer of zlib output compression (1) in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/functions.php on line 4757
[30-Apr-2021 14:40:31 UTC] PHP Notice:  ob_end_flush(): failed to send buffer of zlib output compression (1) in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/functions.php on line 4757
[30-Apr-2021 14:40:31 UTC] PHP Notice:  ob_end_flush(): failed to send buffer of zlib output compression (1) in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/functions.php on line 4757
[30-Apr-2021 14:40:34 UTC] PHP Notice:  ob_end_flush(): failed to send buffer of zlib output compression (1) in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/functions.php on line 4757
[30-Apr-2021 14:40:34 UTC] PHP Notice:  ob_end_flush(): failed to send buffer of zlib output compression (1) in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/functions.php on line 4757
[30-Apr-2021 14:40:37 UTC] PHP Notice:  ob_end_flush(): failed to send buffer of zlib output compression (1) in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/functions.php on line 4757
[30-Apr-2021 14:40:37 UTC] PHP Notice:  ob_end_flush(): failed to send buffer of zlib output compression (1) in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/functions.php on line 4757
[30-Apr-2021 14:40:38 UTC] PHP Fatal error:  Uncaught Error: Call to undefined method WPGraphQL\WooCommerce\Utils\QL_Session_Handler::get_cart() in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-content/plugins/cart-rest-api-for-woocommerce/includes/class-cocart-woocommerce.php:128
Stack trace:
#0 /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/class-wp-hook.php(292): CoCart_WooCommerce::load_cart_from_session('')
#1 /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters('', Array)
#2 /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/plugin.php(484): WP_Hook->do_action(Array)
#3 /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-content/plugins/woocommerce/includes/class-wc-cart-session.php(72): do_action('woocommerce_loa...')
#4 /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/class-wp-hook.php(292): WC_Cart_Session->get_cart_from_session('')
#5 /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/class-wp-hook.php(316): WP_Hook->apply_f in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-content/plugins/cart-rest-api-for-woocommerce/includes/class-cocart-woocommerce.php on line 128
[30-Apr-2021 14:44:59 UTC] PHP Notice:  ob_end_flush(): failed to send buffer of zlib output compression (1) in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/functions.php on line 4757
[30-Apr-2021 14:44:59 UTC] PHP Notice:  ob_end_flush(): failed to send buffer of zlib output compression (1) in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/functions.php on line 4757
[30-Apr-2021 14:45:01 UTC] PHP Fatal error:  Uncaught Error: Call to undefined method WPGraphQL\WooCommerce\Utils\QL_Session_Handler::get_cart() in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-content/plugins/cart-rest-api-for-woocommerce/includes/class-cocart-woocommerce.php:128
Stack trace:
#0 /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/class-wp-hook.php(292): CoCart_WooCommerce::load_cart_from_session('')
#1 /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters('', Array)
#2 /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/plugin.php(484): WP_Hook->do_action(Array)
#3 /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-content/plugins/woocommerce/includes/class-wc-cart-session.php(72): do_action('woocommerce_loa...')
#4 /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/class-wp-hook.php(292): WC_Cart_Session->get_cart_from_session('')
#5 /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/class-wp-hook.php(316): WP_Hook->apply_f in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-content/plugins/cart-rest-api-for-woocommerce/includes/class-cocart-woocommerce.php on line 128
[30-Apr-2021 14:46:26 UTC] PHP Notice:  ob_end_flush(): failed to send buffer of zlib output compression (1) in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/functions.php on line 4757
[30-Apr-2021 14:46:26 UTC] PHP Notice:  ob_end_flush(): failed to send buffer of zlib output compression (1) in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/functions.php on line 4757
[30-Apr-2021 14:46:30 UTC] PHP Notice:  ob_end_flush(): failed to send buffer of zlib output compression (1) in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/functions.php on line 4757
[30-Apr-2021 14:46:30 UTC] PHP Notice:  ob_end_flush(): failed to send buffer of zlib output compression (1) in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/functions.php on line 4757
[30-Apr-2021 14:46:53 UTC] PHP Notice:  ob_end_flush(): failed to send buffer of zlib output compression (1) in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/functions.php on line 4757
[30-Apr-2021 14:46:53 UTC] PHP Notice:  ob_end_flush(): failed to send buffer of zlib output compression (1) in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/functions.php on line 4757
[30-Apr-2021 14:46:55 UTC] PHP Notice:  ob_end_flush(): failed to send buffer of zlib output compression (1) in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/functions.php on line 4757
[30-Apr-2021 14:46:55 UTC] PHP Notice:  ob_end_flush(): failed to send buffer of zlib output compression (1) in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/functions.php on line 4757
[30-Apr-2021 14:46:56 UTC] PHP Notice:  ob_end_flush(): failed to send buffer of zlib output compression (1) in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/functions.php on line 4757
[30-Apr-2021 14:46:56 UTC] PHP Notice:  ob_end_flush(): failed to send buffer of zlib output compression (1) in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/functions.php on line 4757
[30-Apr-2021 14:47:00 UTC] PHP Notice:  ob_end_flush(): failed to send buffer of zlib output compression (1) in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/functions.php on line 4757
[30-Apr-2021 14:47:00 UTC] PHP Notice:  ob_end_flush(): failed to send buffer of zlib output compression (1) in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/functions.php on line 4757
[30-Apr-2021 14:47:22 UTC] PHP Notice:  ob_end_flush(): failed to send buffer of zlib output compression (1) in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/functions.php on line 4757
[30-Apr-2021 14:47:22 UTC] PHP Notice:  ob_end_flush(): failed to send buffer of zlib output compression (1) in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/functions.php on line 4757
[30-Apr-2021 14:47:22 UTC] PHP Notice:  ob_end_flush(): failed to send buffer of zlib output compression (1) in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/functions.php on line 4757
[30-Apr-2021 14:47:22 UTC] PHP Notice:  ob_end_flush(): failed to send buffer of zlib output compression (1) in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/functions.php on line 4757
[30-Apr-2021 14:47:28 UTC] PHP Notice:  ob_end_flush(): failed to send buffer of zlib output compression (1) in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/functions.php on line 4757
[30-Apr-2021 14:47:28 UTC] PHP Notice:  ob_end_flush(): failed to send buffer of zlib output compression (1) in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/functions.php on line 4757
[30-Apr-2021 14:47:37 UTC] PHP Notice:  ob_end_flush(): failed to send buffer of zlib output compression (1) in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/functions.php on line 4757
[30-Apr-2021 14:47:37 UTC] PHP Notice:  ob_end_flush(): failed to send buffer of zlib output compression (1) in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/functions.php on line 4757
[30-Apr-2021 14:47:53 UTC] PHP Notice:  ob_end_flush(): failed to send buffer of zlib output compression (1) in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/functions.php on line 4757
[30-Apr-2021 14:47:53 UTC] PHP Notice:  ob_end_flush(): failed to send buffer of zlib output compression (1) in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/functions.php on line 4757
[30-Apr-2021 14:48:04 UTC] PHP Notice:  ob_end_flush(): failed to send buffer of zlib output compression (1) in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/functions.php on line 4757
[30-Apr-2021 14:48:04 UTC] PHP Notice:  ob_end_flush(): failed to send buffer of zlib output compression (1) in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/functions.php on line 4757
[30-Apr-2021 14:48:13 UTC] PHP Notice:  ob_end_flush(): failed to send buffer of zlib output compression (1) in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/functions.php on line 4757
[30-Apr-2021 14:48:13 UTC] PHP Notice:  ob_end_flush(): failed to send buffer of zlib output compression (1) in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/functions.php on line 4757
[30-Apr-2021 14:48:13 UTC] PHP Fatal error:  Uncaught Error: Call to undefined method WPGraphQL\WooCommerce\Utils\QL_Session_Handler::get_cart() in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-content/plugins/cart-rest-api-for-woocommerce/includes/class-cocart-woocommerce.php:128
Stack trace:
#0 /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/class-wp-hook.php(292): CoCart_WooCommerce::load_cart_from_session('')
#1 /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters('', Array)
#2 /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/plugin.php(484): WP_Hook->do_action(Array)
#3 /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-content/plugins/woocommerce/includes/class-wc-cart-session.php(72): do_action('woocommerce_loa...')
#4 /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/class-wp-hook.php(292): WC_Cart_Session->get_cart_from_session('')
#5 /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/class-wp-hook.php(316): WP_Hook->apply_f in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-content/plugins/cart-rest-api-for-woocommerce/includes/class-cocart-woocommerce.php on line 128
[30-Apr-2021 14:48:16 UTC] PHP Fatal error:  Uncaught Error: Call to undefined method WPGraphQL\WooCommerce\Utils\QL_Session_Handler::get_cart() in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-content/plugins/cart-rest-api-for-woocommerce/includes/class-cocart-woocommerce.php:128
Stack trace:
#0 /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/class-wp-hook.php(292): CoCart_WooCommerce::load_cart_from_session('')
#1 /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters('', Array)
#2 /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/plugin.php(484): WP_Hook->do_action(Array)
#3 /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-content/plugins/woocommerce/includes/class-wc-cart-session.php(72): do_action('woocommerce_loa...')
#4 /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/class-wp-hook.php(292): WC_Cart_Session->get_cart_from_session('')
#5 /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/class-wp-hook.php(316): WP_Hook->apply_f in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-content/plugins/cart-rest-api-for-woocommerce/includes/class-cocart-woocommerce.php on line 128
[30-Apr-2021 14:48:51 UTC] PHP Notice:  ob_end_flush(): failed to send buffer of zlib output compression (1) in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/functions.php on line 4757
[30-Apr-2021 14:48:51 UTC] PHP Notice:  ob_end_flush(): failed to send buffer of zlib output compression (1) in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/functions.php on line 4757
[30-Apr-2021 14:49:02 UTC] PHP Notice:  ob_end_flush(): failed to send buffer of zlib output compression (1) in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/functions.php on line 4757
[30-Apr-2021 14:49:02 UTC] PHP Notice:  ob_end_flush(): failed to send buffer of zlib output compression (1) in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/functions.php on line 4757
[30-Apr-2021 14:49:05 UTC] PHP Notice:  ob_end_flush(): failed to send buffer of zlib output compression (1) in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/functions.php on line 4757
[30-Apr-2021 14:49:05 UTC] PHP Notice:  ob_end_flush(): failed to send buffer of zlib output compression (1) in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/functions.php on line 4757
[30-Apr-2021 14:49:09 UTC] PHP Notice:  ob_end_flush(): failed to send buffer of zlib output compression (1) in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/functions.php on line 4757
[30-Apr-2021 14:49:09 UTC] PHP Notice:  ob_end_flush(): failed to send buffer of zlib output compression (1) in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/functions.php on line 4757
[30-Apr-2021 14:49:10 UTC] PHP Fatal error:  Uncaught Error: Call to undefined method WPGraphQL\WooCommerce\Utils\QL_Session_Handler::get_cart() in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-content/plugins/cart-rest-api-for-woocommerce/includes/class-cocart-woocommerce.php:128
Stack trace:
#0 /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/class-wp-hook.php(292): CoCart_WooCommerce::load_cart_from_session('')
#1 /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters('', Array)
#2 /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/plugin.php(484): WP_Hook->do_action(Array)
#3 /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-content/plugins/woocommerce/includes/class-wc-cart-session.php(72): do_action('woocommerce_loa...')
#4 /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/class-wp-hook.php(292): WC_Cart_Session->get_cart_from_session('')
#5 /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/class-wp-hook.php(316): WP_Hook->apply_f in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-content/plugins/cart-rest-api-for-woocommerce/includes/class-cocart-woocommerce.php on line 128
[30-Apr-2021 14:49:14 UTC] PHP Notice:  ob_end_flush(): failed to send buffer of zlib output compression (1) in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/functions.php on line 4757
[30-Apr-2021 14:49:14 UTC] PHP Notice:  ob_end_flush(): failed to send buffer of zlib output compression (1) in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/functions.php on line 4757
[30-Apr-2021 14:49:14 UTC] PHP Notice:  ob_end_flush(): failed to send buffer of zlib output compression (1) in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/functions.php on line 4757
[30-Apr-2021 14:49:14 UTC] PHP Notice:  ob_end_flush(): failed to send buffer of zlib output compression (1) in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/functions.php on line 4757
[30-Apr-2021 14:49:15 UTC] PHP Fatal error:  Uncaught Error: Call to undefined method WPGraphQL\WooCommerce\Utils\QL_Session_Handler::get_cart() in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-content/plugins/cart-rest-api-for-woocommerce/includes/class-cocart-woocommerce.php:128
Stack trace:
#0 /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/class-wp-hook.php(292): CoCart_WooCommerce::load_cart_from_session('')
#1 /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters('', Array)
#2 /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/plugin.php(484): WP_Hook->do_action(Array)
#3 /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-content/plugins/woocommerce/includes/class-wc-cart-session.php(72): do_action('woocommerce_loa...')
#4 /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/class-wp-hook.php(292): WC_Cart_Session->get_cart_from_session('')
#5 /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/class-wp-hook.php(316): WP_Hook->apply_f in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-content/plugins/cart-rest-api-for-woocommerce/includes/class-cocart-woocommerce.php on line 128
[30-Apr-2021 14:49:21 UTC] PHP Fatal error:  Uncaught Error: Call to undefined method WPGraphQL\WooCommerce\Utils\QL_Session_Handler::get_cart() in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-content/plugins/cart-rest-api-for-woocommerce/includes/class-cocart-woocommerce.php:128
Stack trace:
#0 /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/class-wp-hook.php(292): CoCart_WooCommerce::load_cart_from_session('')
#1 /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters('', Array)
#2 /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/plugin.php(484): WP_Hook->do_action(Array)
#3 /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-content/plugins/woocommerce/includes/class-wc-cart-session.php(72): do_action('woocommerce_loa...')
#4 /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/class-wp-hook.php(292): WC_Cart_Session->get_cart_from_session('')
#5 /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/class-wp-hook.php(316): WP_Hook->apply_f in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-content/plugins/cart-rest-api-for-woocommerce/includes/class-cocart-woocommerce.php on line 128
[30-Apr-2021 14:50:03 UTC] PHP Notice:  ob_end_flush(): failed to send buffer of zlib output compression (1) in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/functions.php on line 4757
[30-Apr-2021 14:50:03 UTC] PHP Notice:  ob_end_flush(): failed to send buffer of zlib output compression (1) in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/functions.php on line 4757
[30-Apr-2021 14:51:06 UTC] PHP Notice:  ob_end_flush(): failed to send buffer of zlib output compression (1) in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/functions.php on line 4757
[30-Apr-2021 14:51:06 UTC] PHP Notice:  ob_end_flush(): failed to send buffer of zlib output compression (1) in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/functions.php on line 4757
[30-Apr-2021 14:51:56 UTC] PHP Notice:  ob_end_flush(): failed to send buffer of zlib output compression (1) in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/functions.php on line 4757
[30-Apr-2021 14:51:56 UTC] PHP Notice:  ob_end_flush(): failed to send buffer of zlib output compression (1) in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/functions.php on line 4757
[30-Apr-2021 14:52:06 UTC] PHP Notice:  ob_end_flush(): failed to send buffer of zlib output compression (1) in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/functions.php on line 4757
[30-Apr-2021 14:52:06 UTC] PHP Notice:  ob_end_flush(): failed to send buffer of zlib output compression (1) in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/functions.php on line 4757
[30-Apr-2021 14:52:20 UTC] PHP Notice:  ob_end_flush(): failed to send buffer of zlib output compression (1) in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/functions.php on line 4757
[30-Apr-2021 14:52:20 UTC] PHP Notice:  ob_end_flush(): failed to send buffer of zlib output compression (1) in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/functions.php on line 4757
[30-Apr-2021 14:52:23 UTC] PHP Notice:  ob_end_flush(): failed to send buffer of zlib output compression (1) in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/functions.php on line 4757
[30-Apr-2021 14:52:23 UTC] PHP Notice:  ob_end_flush(): failed to send buffer of zlib output compression (1) in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/functions.php on line 4757
[30-Apr-2021 14:52:41 UTC] PHP Notice:  ob_end_flush(): failed to send buffer of zlib output compression (1) in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/functions.php on line 4757
[30-Apr-2021 14:52:41 UTC] PHP Notice:  ob_end_flush(): failed to send buffer of zlib output compression (1) in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/functions.php on line 4757
[30-Apr-2021 14:53:05 UTC] PHP Notice:  ob_end_flush(): failed to send buffer of zlib output compression (1) in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/functions.php on line 4757
[30-Apr-2021 14:53:05 UTC] PHP Notice:  ob_end_flush(): failed to send buffer of zlib output compression (1) in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/functions.php on line 4757
[30-Apr-2021 14:53:32 UTC] PHP Notice:  ob_end_flush(): failed to send buffer of zlib output compression (1) in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/functions.php on line 4757
[30-Apr-2021 14:53:32 UTC] PHP Notice:  ob_end_flush(): failed to send buffer of zlib output compression (1) in /home/clients/1af26801e7545bf2a2540dfea6d5cd99/web/wp-includes/functions.php on line 4757
`

**Comment by vince93290** [comment]
> WP-GraphQL WooCommerce uses it's own session handler. Is there a reason your using the WC extension too

sorry i dont understand

**Comment by vince93290** [comment]
i use graphql woocommerce plug in to fetch product data.

**Comment by seb86** [comment]
There is a conflict because both CoCart and WP-GraphQL WooCommerce use there own custom session handler. According to the error log, CoCart is failing because WP-GraphQL WooCommerce has taken over the session handler.

**Comment by vince93290** [comment]
> There is a conflict because both CoCart and WP-GraphQL WooCommerce use there own custom session handler. According to the error log, CoCart is failing because WP-GraphQL WooCommerce has taken over the session handler.

so it will be impossible to make the two plug-ins work together?

**Comment by seb86** [comment]
I've not had much of a look at WP-GraphQL in general. I just know that the WooCommerce extension uses it's own session handler.

I don't know how they could work together. Will see if I can get someone from WP-GraphQL community to provide some information.

**Comment by vince93290** [comment]
Is it strange that it works with version 2.9.3 and not 3?

**Comment by seb86** [comment]
v3 has some changes to when the session handler is loaded for better performance.

**Comment by seb86** [comment]
So I just got quick word from **Jason Bahl** who is the creator of WP-GraphQL and he helped me identify when a graphql request is being made `is_graphql_http_request()` so I will add that to CoCart for another release candidate.

If you could copy and paste your graphql request so that I can test it out that would be great. Don't forget to format it as `code`.

Best to do like so:

```txt
```json
code goes here

```

**Comment by vince93290** [comment]
```json

query MyQuery {
    products {
      edges {
        node {
          description
          date
          onSale
          name
          slug
          type
          productCategories {
            nodes {
              name
            }
          }
          id
          image {
            link
            sourceUrl
            slug
          }
        }
      }
    }
  }

**Comment by seb86** [comment]
Thank you @vince93290 

That worked great. Still testing to make sure it did not break the use of loading the cart from session as designed.

**Comment by vince93290** [comment]
> Thank you @vince93290
> 
> That worked great. Still testing to make sure it did not break the use of loading the cart from session as designed.

very good news I am in a hurry to be able to test

**Comment by seb86** [comment]
New RC ready to test @vince93290 

https://github.com/co-cart/co-cart/releases/tag/v3.0.0-rc.2

**Comment by vince93290** [comment]
> New RC ready to test @vince93290
> 
> https://github.com/co-cart/co-cart/releases/tag/v3.0.0-rc.2

Nice i'm a little bizzi this week end i will test tomorow.
