### ISSUE TITLE
Activating the plug-in makes the site unusable

### ISSUE THREAD

**Issue by cha0ran** [co-cart/co-cart#256]
## Describe the bug

When I activate the plugin, there is an error on the frontend of the site, saying "There has been a critical error on this website."
But it doesn't affect the admin backend

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of CoCart on GitHub (this is **not** the same version as on WordPress.org!)
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional)
- [x] I have installed the requirements to run this plugin.

## Steps to reproduce the issue

1. Activate CoCart
2. Open home page

## Screenshots

![QQ20210723-110510@2x.png](https://i.loli.net/2021/07/23/VsHGXbQPSAfovF9.png)

## Isolating the problem

- [x] This bug happens with only WooCommerce and CoCart plugin are active.
- [ ] This bug happens with a default WordPress theme active.
- [ ] This bug happens with the WordPress theme Storefront active.
- [x] This bug happens with the latest release of WooCommerce active.
- [ ] This bug happens only when I authenticate as a customer.
- [ ] This bug happens only when I authenticate as administrator.
- [x] I can reproduce this bug consistently using the steps above.

## WordPress Environment

<details>
```

### WordPress Environment ###

WordPress address (URL): https://www.happyierfriday.com
Site address (URL): https://www.happyierfriday.com
WC Version: 5.1.1
REST API Version: ✔ 5.1.1
WC Blocks Version: ✔ 4.4.3
Action Scheduler Version: ✔ 3.1.6
WC Admin Version: ✔ 2.0.2
Log Directory Writable: ✔
WP Version: 5.8
WP Multisite: ——
WP Memory Limit: 1 GB
WP Debug Mode: ——
WP Cron: ✔
Language: en_US
External object cache: ——

### Server Environment ###

Server Info: nginx/1.18.0
PHP Version: 7.4.3
PHP Post Max Size: 50 MB
PHP Time Limit: 0
PHP Max Input Vars: 1000
cURL Version: 7.68.0，OpenSSL/1.1.1f
SUHOSIN Installed: ——
MySQL Version: 8.0.25-0ubuntu0.20.04.1
Max Upload Size: 20 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ❌您的服务器没有启用SoapClient类 - 一些使用 SOAP 的网关插件可能无法按预期工作。
DOMDocument: ❌您的服务器没有启用DOMDocument类 - HTML/Multipart 电子邮件以及一些扩展在没有 DOMDocument 的情况下将无法工作。
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 5.1.1
WC Database Prefix: wp_
Total Database Size: 901.25MB
Database Data Size: 552.21MB
Database Index Size: 349.04MB
wp_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_order_items: Data: 6.52MB + Index: 2.52MB + Engine InnoDB
wp_woocommerce_order_itemmeta: Data: 107.64MB + Index: 40.14MB + Engine InnoDB
wp_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_woocommerce_payment_tokens: Data: 0.06MB + Index: 0.02MB + Engine InnoDB
wp_woocommerce_payment_tokenmeta: Data: 0.11MB + Index: 0.14MB + Engine InnoDB
wp_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_actions: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wp_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_actionscheduler_logs: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_adtribes_my_conversions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_berocket_termmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_braapf_product_stock_status_parent: Data: 0.23MB + Index: 0.11MB + Engine InnoDB
wp_braapf_product_variation_attributes: Data: 0.45MB + Index: 1.02MB + Engine InnoDB
wp_braapf_term_taxonomy_hierarchical: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_braapf_variation_attributes: Data: 0.09MB + Index: 0.16MB + Engine InnoDB
wp_clickervolt_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_clickervolt_actions_summary: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_clickervolt_aids: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_clickervolt_clicks: Data: 5.75MB + Index: 33.75MB + Engine InnoDB
wp_clickervolt_custom_reports: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_clickervolt_devices: Data: 6.52MB + Index: 9.09MB + Engine InnoDB
wp_clickervolt_external_ids: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_clickervolt_geos: Data: 1.52MB + Index: 5.23MB + Engine InnoDB
wp_clickervolt_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_clickervolt_parallel_ids: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_clickervolt_referrers: Data: 5.52MB + Index: 0.00MB + Engine InnoDB
wp_clickervolt_source_templates: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_clickervolt_stats_base: Data: 0.27MB + Index: 0.06MB + Engine InnoDB
wp_clickervolt_stats_whole_path: Data: 0.58MB + Index: 0.36MB + Engine InnoDB
wp_clickervolt_stats_whole_path_devices: Data: 4.66MB + Index: 2.63MB + Engine InnoDB
wp_clickervolt_stats_whole_path_geos: Data: 4.66MB + Index: 2.63MB + Engine InnoDB
wp_clickervolt_stats_whole_path_referrers: Data: 3.66MB + Index: 2.63MB + Engine InnoDB
wp_clickervolt_stats_whole_path_var1: Data: 0.61MB + Index: 0.39MB + Engine InnoDB
wp_clickervolt_stats_whole_path_var10: Data: 0.61MB + Index: 0.39MB + Engine InnoDB
wp_clickervolt_stats_whole_path_var2: Data: 0.61MB + Index: 0.39MB + Engine InnoDB
wp_clickervolt_stats_whole_path_var3: Data: 0.61MB + Index: 0.39MB + Engine InnoDB
wp_clickervolt_stats_whole_path_var4: Data: 0.61MB + Index: 0.39MB + Engine InnoDB
wp_clickervolt_stats_whole_path_var5: Data: 0.61MB + Index: 0.39MB + Engine InnoDB
wp_clickervolt_stats_whole_path_var6: Data: 0.61MB + Index: 0.39MB + Engine InnoDB
wp_clickervolt_stats_whole_path_var7: Data: 0.61MB + Index: 0.39MB + Engine InnoDB
wp_clickervolt_stats_whole_path_var8: Data: 0.61MB + Index: 0.39MB + Engine InnoDB
wp_clickervolt_stats_whole_path_var9: Data: 0.61MB + Index: 0.39MB + Engine InnoDB
wp_clickervolt_suspicious_clicks: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_clickervolt_urls_paths: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_cocart_carts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_commentmeta: Data: 0.14MB + Index: 0.25MB + Engine InnoDB
wp_comments: Data: 12.52MB + Index: 13.09MB + Engine InnoDB
wp_frmt_form_entry: Data: 0.11MB + Index: 0.17MB + Engine InnoDB
wp_frmt_form_entry_meta: Data: 1.52MB + Index: 0.77MB + Engine InnoDB
wp_frmt_form_views: Data: 0.05MB + Index: 0.06MB + Engine InnoDB
wp_ig_actions: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_ig_blocked_emails: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ig_campaigns: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_ig_contact_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_ig_contactmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_ig_contacts: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_ig_contacts_ips: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ig_forms: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ig_links: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_ig_lists: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ig_lists_contacts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ig_mailing_queue: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_ig_queue: Data: 0.02MB + Index: 0.13MB + Engine InnoDB
wp_ig_sending_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ig_workflows: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_ig_workflows_queue: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_imagify_files: Data: 0.17MB + Index: 0.20MB + Engine InnoDB
wp_imagify_folders: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_mailchimp_carts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_mailchimp_jobs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_nm_personalized: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_options: Data: 4.44MB + Index: 1.66MB + Engine InnoDB
wp_pmxe_exports: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxe_google_cats: Data: 0.39MB + Index: 0.00MB + Engine InnoDB
wp_pmxe_posts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_pmxe_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_postmeta: Data: 114.66MB + Index: 112.33MB + Engine InnoDB
wp_posts: Data: 25.52MB + Index: 7.06MB + Engine InnoDB
wp_refersion_cart_tracking: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_s2w_error_product_images: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_sfa_abandoned_carts: Data: 79.59MB + Index: 0.00MB + Engine InnoDB
wp_simple_history: Data: 36.58MB + Index: 12.06MB + Engine InnoDB
wp_simple_history_contexts: Data: 84.63MB + Index: 59.19MB + Engine InnoDB
wp_social_users: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_statistics_exclusions: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_statistics_historical: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_statistics_pages: Data: 0.11MB + Index: 0.31MB + Engine InnoDB
wp_statistics_search: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_statistics_useronline: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_statistics_visit: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_statistics_visitor: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_term_relationships: Data: 0.41MB + Index: 0.34MB + Engine InnoDB
wp_term_taxonomy: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_termmeta: Data: 0.17MB + Index: 0.20MB + Engine InnoDB
wp_terms: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wp_usermeta: Data: 12.52MB + Index: 13.03MB + Engine InnoDB
wp_users: Data: 1.52MB + Index: 0.61MB + Engine InnoDB
wp_wc_admin_note_actions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_admin_notes: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wp_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wp_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_wc_product_meta_lookup: Data: 1.52MB + Index: 1.17MB + Engine InnoDB
wp_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_wcp_pages: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wp_wcp_products: Data: 0.19MB + Index: 0.28MB + Engine InnoDB
wp_wcp_visitor: Data: 1.52MB + Index: 0.67MB + Engine InnoDB
wp_wcp_visitors: Data: 0.30MB + Index: 0.42MB + Engine InnoDB
wp_wdcp_subscribe_email: Data: 2.52MB + Index: 3.00MB + Engine InnoDB
wp_wdr_order_discounts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wdr_order_item_discounts: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wdr_rules: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpam_actions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpam_affiliates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpam_affiliates_fields: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpam_creatives: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpam_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpam_impressions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpam_messages: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpam_paypal_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpam_tracking_tokens: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpam_tracking_tokens_purchase_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpam_transactions: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wp_wpmailsmtp_tasks_meta: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wp_yith_wcwl: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yith_wcwl_lists: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wp_yoast_indexable: Data: 11.52MB + Index: 11.58MB + Engine InnoDB
wp_yoast_indexable_hierarchy: Data: 1.52MB + Index: 3.44MB + Engine InnoDB
wp_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wp_yoast_primary_term: Data: 0.08MB + Index: 0.09MB + Engine InnoDB
wp_yoast_prominent_words: Data: 0.13MB + Index: 0.17MB + Engine InnoDB
wp_yoast_seo_links: Data: 1.52MB + Index: 0.53MB + Engine InnoDB

### Post Type Counts ###

al_product: 1
attachment: 11291
blocks: 8
br_product_filter: 3
custom_css: 1
es_template: 2
featured_item: 8
forminator_forms: 2
mc4wp-form: 1
nav_menu_item: 42
oembed_cache: 73
page: 137
post: 12
product: 1017
product_variation: 4242
raccartlist: 84
racemailtemplate: 1
racmaillog: 29
revision: 2623
shop_coupon: 199
shop_order_refund: 1450
size-chart: 393
woocommerce-lookbook: 14
wpcf7_contact_form: 5

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ✔

### Active Plugins (45) ###

WP Affiliate Manager: by wp.insider
wpaffiliatemgr – 2.8.3

Autoptimize: by Frank Goossens (futtta) – 2.8.3
Buy Now Button for WooCommerce: by wpismylife – 1.0.0
CoCart Lite: by Sébastien Dumont – 3.0.10
ClickerVolt (Premium): by ClickerVolt.com – 1.168
Contact Form 7: by Takayuki Miyoshi – 5.4
Dianxiaomi - WooCommerce ERP - 20210331: by Dianxiaomi – 1.0.1a
Google Customer Reviews for WooCommerce: by eCreations – 2.6.12
Flexible Shipping: by WP Desk – 4.2.0
Forminator: by WPMU DEV – 1.14.9
Insert Headers and Footers: by WPBeginner – 1.5.0
Klarna Payments for WooCommerce: by krokedil
klarna
automattic – 2.4.3

Max Mega Menu: by megamenu.com – 2.9.3
PW WooCommerce Bulk Edit: by Pimwick
LLC – 2.88

PW WooCommerce Gift Cards Pro: by Pimwick
LLC – 1.304

Simple History: by Pär Thernström – 2.42.0
Abandoned Cart Reports For WooCommerce: by Small Fish Analytics – 2.6.2
Product Size Charts Plugin for WooCommerce Premium: by theDotstore – 2.1.0
Product Size Charts Plugin for WooCommerce Premium: by theDotstore – 2.1.0
Woo Data Center Pro: by  – 1.0.4
LookBook for WooCommerce: by VillaTheme – 1.0.7.2
WPC Product Bundles for WooCommerce (Premium): by WPClever – 5.5.2
Product Feed PRO for WooCommerce: by AdTribes.io – 9.9.9
Variation Images Gallery for WooCommerce: by RadiusTheme – 1.1.23.2
Variation Swatches for WooCommerce - Pro: by Emran Ahmed – 1.1.14
Variation Swatches for WooCommerce: by Emran Ahmed – 1.1.14
Woo Custom Pro: by  – 1.6.7
Advanced AJAX Product Filters for WooCommerce: by BeRocket – 1.5.3
WooCommerce Extended Coupon Features PRO: by Soft79 – 3.1.1
WooCommerce PayPal Checkout Gateway: by WooCommerce – 2.1.1
WooCommerce Stripe Gateway: by WooCommerce – 5.1.0
WooCommerce PayPal Payments: by WooCommerce – 1.2.1
WooCommerce Photo Reviews Premium: by VillaTheme – 1.1.4.9
WooCommerce Shipping & Tax: by Automattic – 1.25.11
WooCommerce: by Automattic – 5.1.1
WooSidebars: by WooCommerce – 1.4.5
WordPress Importer: by wordpressdotorg – 0.7
Yoast SEO Premium: by Team Yoast – 16.4
Yoast SEO: by Team Yoast – 16.4
Worldpay: by ygFYW – 4.6
WP Mail SMTP: by WPForms – 2.7.0
Custom Product Tabs for WooCommerce: by YIKES
Inc. – 1.7.7

Z_lastload_lll_customize_variationgallery: by Lily Law – 1.0.1
Z LAT: by Lily Law – 2.1.3
Z Sticky Add to Cart: by Lily Law – 1.1.4

### Inactive Plugins (3) ###

Klaviyo: by Klaviyo
Inc. – 2.4.0

PixelYourSite Pinterest: by PixelYourSite – 3.0.0
PixelYourSite PRO: by PixelYourSite – 8.0.4

### Settings ###

API Enabled: –
Force SSL: –
Currency: USD ($)
Currency Position: left
Thousand Separator: ,
Decimal Separator: .
Number of Decimals: 0
Taxonomies: Product Types: external (external)
grouped (grouped)
pw gift card (pw-gift-card)
simple (simple)
variable (variable)
woosb (woosb)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –

### WC Pages ###

Shop base: #324 - /shop/
Cart: #7 - /cart/
Checkout: #8 - /checkout/
My account: #9 - /my-account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: flatsome-child
Version: 3.0
Author URL: 
Child Theme: ✔
Parent Theme Name: Flatsome
Parent Theme Version: 3.13.1
Parent Theme Author URL: http://www.uxthemes.com/
WooCommerce Support: ✔

### Templates ###

Overrides: flatsome/woocommerce/archive-product.php
flatsome/woocommerce/cart/cart-empty.php
flatsome/woocommerce/cart/cart-shipping.php
flatsome/woocommerce/cart/cart.php
flatsome/woocommerce/checkout/form-checkout.php
flatsome/woocommerce/checkout/form-coupon.php
flatsome/woocommerce/checkout/terms.php
flatsome/woocommerce/checkout/thankyou.php
flatsome/woocommerce/content-product-cat.php
flatsome/woocommerce/content-product.php
flatsome/woocommerce/content-single-product.php
flatsome/woocommerce/content-widget-product.php
flatsome/woocommerce/global/breadcrumb.php
flatsome/woocommerce/global/quantity-input.php
flatsome/woocommerce/global/wrapper-end.php
flatsome/woocommerce/global/wrapper-start.php
flatsome/woocommerce/loop/loop-end.php
flatsome/woocommerce/loop/loop-start.php
flatsome/woocommerce/loop/pagination.php
flatsome/woocommerce/loop/result-count.php
flatsome/woocommerce/loop/sale-flash.php
flatsome/woocommerce/myaccount/form-login.php
flatsome/woocommerce/myaccount/navigation.php
flatsome/woocommerce/notices/error.php
flatsome/woocommerce/notices/notice.php
flatsome/woocommerce/notices/success.php
flatsome/woocommerce/product-searchform.php
flatsome/woocommerce/single-product/photoswipe.php
flatsome/woocommerce/single-product/price.php
/data/html/www.happyierfriday.com/wp-content/plugins/woo-product-variation-gallery/templates/product-images.php
/data/html/www.happyierfriday.com/wp-content/plugins/woo-product-variation-gallery/templates/product-thumbnails.php
flatsome/woocommerce/single-product/rating.php
flatsome/woocommerce/single-product/related.php
flatsome/woocommerce/single-product/review.php
flatsome/woocommerce/single-product/sale-flash.php
flatsome/woocommerce/single-product/share.php
flatsome/woocommerce/single-product/short-description.php
flatsome/woocommerce/single-product/tabs/tabs.php
flatsome/woocommerce/single-product/title.php
flatsome/woocommerce/single-product/up-sells.php
flatsome-child/woocommerce/single-product- reviews.php 、flatsome/woocommerce/single-product.php、flatsome/woocommerce/content-product_cat.php


### Action Scheduler ###

完全的: 6
Oldest: 2021-07-06 00:35:15 -0700
Newest: 2021-07-22 18:33:30 -0700

失败的: 1
Oldest: 2021-05-25 20:11:59 -0700
Newest: 2021-05-25 20:11:59 -0700


### CoCart ###

Version: 3.0.10
Database Version: 3.0.10
Install Date: 2021 年 7 月 22 日
Carts in Session: 0
Carts Active: 0 出 0 会话。
Carts Expiring Soon: 0 出 0 会话。
Carts Expired: 0 出 0 会话。
Carts Source (by CoCart): 0
Carts Source (by Web): 0
Carts Source (by Other): 0

### Status report information ###

Generated at: 2021-07-22 20:10:40 -07:00
```
</details>

## Additional context

none.

**Comment by seb86** [comment]
Enable debug mode on your site and report any related CoCart errors please that gets logged. While I feel bad that my plugin has done this to the front-end upon activation, this is most likely a compatibility error. What you sent is not really enough to solve the issue.

**Comment by cha0ran** [comment]
@seb86 
Ok, I opened is debug and got this error

`
Fatal error: 
Uncaught TypeError: Argument 2 passed to WPDesk\FS\TableRate\FreeShipping\FreeShippingNotice::__construct() must be an instance of WC_Session, instance of CoCart_Session_Handler given, called in /www/wp-content/plugins/flexible-shipping/classes/class-flexible-shipping-plugin.php on line 434 and defined in /www/wp-content/plugins/flexible-shipping/src/WPDesk/FS/TableRate/FreeShipping/FreeShippingNotice.php:38 Stack trace: #0 /www/wp-content/plugins/flexible-shipping/classes/class-flexible-shipping-plugin.php(434): WPDesk\FS\TableRate\FreeShipping\FreeShippingNotice->__construct() #1 /www/wp-includes/class-wp-hook.php(303): Flexible_Shipping_Plugin->init_free_shipping_notice() #2 /www/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters() #3 /www/wp-includes/plugin.php(470): WP_Hook->do_action() #4 /www/wp in /www/wp-content/plugins/flexible-shipping/src/WPDesk/FS/TableRate/FreeShipping/FreeShippingNotice.php on line 38
`

**Comment by seb86** [comment]
That plugin fixed that issue. I suggest you update it.

**Comment by cha0ran** [comment]
The upgrade solved it, thanks a lot 👍
