### ISSUE TITLE
Bug: Uncaught error with no featured image for a variation of a variable product. 

### ISSUE THREAD

**Issue by jnz31** [co-cart/co-cart#416]
## Describe the bug

`<b>Fatal error</b>:  Uncaught TypeError: current(): Argument #1 ($array) must be of type array, bool given in .../cart-rest-api-for-woocommerce/includes/api/cocart/v2/products/class-cocart-products-controller.php:272`

## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `trunk` branch of CoCart on GitHub.
- [x] The issue still exists against the latest `dev` branch of CoCart on GitHub (this is **not** the same version as on WordPress.org!).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional)
- [x] I have installed the requirements to run this plugin.

## Steps to reproduce the issue

1. i created a variable product with 2 variations, but without any images. immediately i get mentioned error, when querying for products (/wp-json/cocart/v2/products/?per_page=30&page=1)
2. this problem occured for me on page 7 og my products. i now created a new product as mentioned above and now i do get that error on page 1, only cocart, woocommerce & twenty-twentyfour theme active. default request, non-authenticated
3. switching to `simple product` resolves the issue.
4. full error: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

<br />
<b>Fatal error</b>:  Uncaught TypeError: current(): Argument #1 ($array) must be of type array, bool given in /var/www/html/web/app/plugins/cart-rest-api-for-woocommerce/includes/api/cocart/v2/products/class-cocart-products-controller.php:272
Stack trace:
#0 /var/www/html/web/app/plugins/cart-rest-api-for-woocommerce/includes/api/cocart/v2/products/class-cocart-products-controller.php(272): current(false)
#1 /var/www/html/web/app/plugins/cart-rest-api-for-woocommerce/includes/api/cocart/v2/products/class-cocart-products-controller.php(209): CoCart_REST_Products_V2_Controller-&gt;get_variations(Object(WC_Product_Variable))
#2 /var/www/html/web/app/plugins/cart-rest-api-for-woocommerce/includes/api/cocart/v2/products/class-cocart-products-controller.php(114): CoCart_REST_Products_V2_Controller-&gt;prepare_object_for_response(Object(WC_Product_Variable), Object(WP_REST_Request))
#3 /var/www/html/web/wp/wp-includes/rest-api/class-wp-rest-server.php(1230): CoCart_REST_Products_V2_Controller-&gt;get_items(Object(WP_REST_Request))
#4 /var/www/html/web/wp/wp-includes/rest-api/class-wp-rest-server.php(1063): WP_REST_Server-&gt;respond_to_request(Object(WP_REST_Request), '/cocart/v2/prod...', Array, NULL)
#5 /var/www/html/web/wp/wp-includes/rest-api/class-wp-rest-server.php(439): WP_REST_Server-&gt;dispatch(Object(WP_REST_Request))
#6 /var/www/html/web/wp/wp-includes/rest-api.php(428): WP_REST_Server-&gt;serve_request('/cocart/v2/prod...')
#7 /var/www/html/web/wp/wp-includes/class-wp-hook.php(324): rest_api_loaded(Object(WP))
#8 /var/www/html/web/wp/wp-includes/class-wp-hook.php(348): WP_Hook-&gt;apply_filters(NULL, Array)
#9 /var/www/html/web/wp/wp-includes/plugin.php(565): WP_Hook-&gt;do_action(Array)
#10 /var/www/html/web/wp/wp-includes/class-wp.php(418): do_action_ref_array('parse_request', Array)
#11 /var/www/html/web/wp/wp-includes/class-wp.php(813): WP-&gt;parse_request('')
#12 /var/www/html/web/wp/wp-includes/functions.php(1336): WP-&gt;main('')
#13 /var/www/html/web/wp/wp-blog-header.php(16): wp()
#14 /var/www/html/web/index.php(6): require('/var/www/html/w...')
#15 {main}
  thrown in <b>/var/www/html/web/app/plugins/cart-rest-api-for-woocommerce/includes/api/cocart/v2/products/class-cocart-products-controller.php</b> on line <b>272</b><br />

## Isolating the problem

- [x] This bug happens with only WooCommerce and CoCart plugin are active.
- [x] This bug happens with a default WordPress theme active.
- [ ] This bug happens with the WordPress theme Storefront active.
- [x] This bug happens with the latest release of WooCommerce active.
- [ ] This bug happens only when I authenticate as a customer.
- [ ] This bug happens only when I authenticate as administrator.
- [x] I can reproduce this bug consistently using the steps above.

## WordPress Environment

<details>
```
### WordPress Environment ###

WordPress address (URL): https://415.xy.ddev.site/wp
Site address (URL): https://415.xy.ddev.site
WC Version: 8.9.3
REST API Version: ✔ 8.9.3
Action Scheduler Version: ✔ 3.7.4
Log Directory Writable: ✔
WP Version: 6.5.4
WP Multisite: –
WP Memory Limit: 1 GB
WP Debug Mode: ✔
WP Cron: ✔
Language: en_US
External object cache: –

### Server Environment ###

Server Info: nginx/1.20.2
PHP Version: 8.1.0
PHP Post Max Size: 100 MB
PHP Time Limit: 600
PHP Max Input Vars: 3000
cURL Version: 7.74.0
OpenSSL/1.1.1k

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.3.32-MariaDB-1:10.3.32+maria~focal-log
Max Upload Size: 100 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

### Database ###

WC Database Version: 8.9.3
WC Database Prefix: wpSD24_
Total Database Size: 65.28MB
Database Data Size: 39.45MB
Database Index Size: 25.83MB
wpSD24_woocommerce_sessions: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpSD24_woocommerce_api_keys: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpSD24_woocommerce_attribute_taxonomies: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpSD24_woocommerce_downloadable_product_permissions: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpSD24_woocommerce_order_items: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpSD24_woocommerce_order_itemmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpSD24_woocommerce_tax_rates: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpSD24_woocommerce_tax_rate_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpSD24_woocommerce_shipping_zones: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpSD24_woocommerce_shipping_zone_locations: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpSD24_woocommerce_shipping_zone_methods: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpSD24_woocommerce_payment_tokens: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpSD24_woocommerce_payment_tokenmeta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpSD24_woocommerce_log: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpSD24_actionscheduler_actions: Data: 1.52MB + Index: 1.38MB + Engine InnoDB
wpSD24_actionscheduler_claims: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpSD24_actionscheduler_groups: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpSD24_actionscheduler_logs: Data: 1.52MB + Index: 0.63MB + Engine InnoDB
wpSD24_aiowps_audit_log: Data: 0.19MB + Index: 0.06MB + Engine InnoDB
wpSD24_aiowps_debug_log: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpSD24_aiowps_events: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpSD24_aiowps_global_meta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpSD24_aiowps_logged_in_users: Data: 0.02MB + Index: 0.08MB + Engine InnoDB
wpSD24_aiowps_login_lockdown: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpSD24_aiowps_message_store: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpSD24_aiowps_permanent_block: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpSD24_cocart_carts: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpSD24_commentmeta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpSD24_comments: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wpSD24_links: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpSD24_options: Data: 4.03MB + Index: 0.36MB + Engine InnoDB
wpSD24_pmxi_files: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpSD24_pmxi_hash: Data: 0.23MB + Index: 0.00MB + Engine InnoDB
wpSD24_pmxi_history: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpSD24_pmxi_images: Data: 1.52MB + Index: 0.00MB + Engine InnoDB
wpSD24_pmxi_imports: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpSD24_pmxi_posts: Data: 0.25MB + Index: 0.00MB + Engine InnoDB
wpSD24_pmxi_templates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpSD24_postmeta: Data: 19.47MB + Index: 16.42MB + Engine InnoDB
wpSD24_posts: Data: 4.52MB + Index: 1.77MB + Engine InnoDB
wpSD24_post_smtp_logmeta: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpSD24_post_smtp_logs: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpSD24_relevanssi: Data: 0.05MB + Index: 0.05MB + Engine InnoDB
wpSD24_relevanssi_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpSD24_relevanssi_stopwords: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpSD24_termmeta: Data: 0.08MB + Index: 0.20MB + Engine InnoDB
wpSD24_terms: Data: 0.05MB + Index: 0.03MB + Engine InnoDB
wpSD24_term_relationships: Data: 1.45MB + Index: 1.52MB + Engine InnoDB
wpSD24_term_taxonomy: Data: 0.06MB + Index: 0.03MB + Engine InnoDB
wpSD24_usermeta: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpSD24_users: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpSD24_wc_admin_notes: Data: 0.06MB + Index: 0.00MB + Engine InnoDB
wpSD24_wc_admin_note_actions: Data: 0.05MB + Index: 0.02MB + Engine InnoDB
wpSD24_wc_category_lookup: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpSD24_wc_customer_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpSD24_wc_download_log: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpSD24_wc_orders: Data: 0.02MB + Index: 0.11MB + Engine InnoDB
wpSD24_wc_orders_meta: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpSD24_wc_order_addresses: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpSD24_wc_order_coupon_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpSD24_wc_order_operational_data: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpSD24_wc_order_product_lookup: Data: 0.02MB + Index: 0.06MB + Engine InnoDB
wpSD24_wc_order_stats: Data: 0.02MB + Index: 0.05MB + Engine InnoDB
wpSD24_wc_order_tax_lookup: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpSD24_wc_pos_grid_tiles: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpSD24_wc_product_attributes_lookup: Data: 0.09MB + Index: 0.08MB + Engine InnoDB
wpSD24_wc_product_download_directories: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpSD24_wc_product_meta_lookup: Data: 0.41MB + Index: 0.70MB + Engine InnoDB
wpSD24_wc_rate_limits: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpSD24_wc_reserved_stock: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpSD24_wc_tax_rate_classes: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpSD24_wc_webhooks: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpSD24_woocommerce_shipping_table_rates: Data: 0.02MB + Index: 0.00MB + Engine InnoDB
wpSD24_yoast_indexable: Data: 2.48MB + Index: 0.86MB + Engine InnoDB
wpSD24_yoast_indexable_hierarchy: Data: 0.09MB + Index: 0.08MB + Engine InnoDB
wpSD24_yoast_migrations: Data: 0.02MB + Index: 0.02MB + Engine InnoDB
wpSD24_yoast_primary_term: Data: 0.02MB + Index: 0.03MB + Engine InnoDB
wpSD24_yoast_seo_links: Data: 0.19MB + Index: 0.13MB + Engine InnoDB

### Post Type Counts ###

attachment: 3820
nav_menu_item: 7
page: 12
pos_outlet: 1
pos_receipt: 1
pos_register: 1
post: 2
product: 967
product_variation: 2404
revision: 12
wp_font_face: 33
wp_font_family: 12
wp_global_styles: 2
wp_navigation: 1

### Security ###

Secure connection (HTTPS): ✔
Hide errors from visitors: ❌Error messages should not be shown to visitors.

### Active Plugins (2) ###

CoCart API - Decoupling Made Easy for WooCommerce: by CoCart Headless
LLC – 4.1.0

WooCommerce: by Automattic – 8.9.3

### Inactive Plugins (35) ###

Advanced Access Manager: by AAM <support@aamplugin.com> – 6.9.31
Advanced Custom Fields PRO: by WP Engine – 6.3.1.2
All In One WP Security: by All In One WP Security & Firewall Team – 5.3.0
CoCart Plus: by CoCart Headless
LLC – 1.4.0

CSV-Export: by Andreas Buss – 1.0.0
Disable Emojis (GDPR friendly): by Ryan Hellyer – 1.7.6
Facebook for WooCommerce: by Facebook – 3.2.4
Gift Wrapper: by Little Package – 6.1.7
Index WP MySQL For Speed: by Oliver Jones
Rick James – 1.4.18

Password Protected: by Password Protected – 2.7.2
PDF Invoices & Packing Slips for WooCommerce: by WP Overnight – 3.8.3
PDF Invoices & Packing Slips for WooCommerce - Premium Templates: by WP Overnight – 2.19.6
PDF Invoices & Packing Slips for WooCommerce - Professional: by WP Overnight – 2.13.8
Perfect Images (Optimize, Rebuild, Replace, Thumbnails, Retina): by Jordy Meow – 6.5.7
PixelYourSite: by PixelYourSite – 9.6.1.1
Point of Sale for WooCommerce: by Actuality Extensions – 6.4.0
Post SMTP: by Post SMTP – 2.9.4
Regenerate Thumbnails: by Alex Mills (Viper007Bond) – 3.1.6
Relevanssi: by Mikko Saari – 4.22.2
REST API Data Localizer: by Brandon Shiluk – 1.0.0
Show Current Template: by JOTAKI Taisuke – 0.5.2
Simple Custom Post Order: by Colorlib – 2.5.7
TikTok: by TikTok – 1.2.6
UpdraftPlus - Backup/Restore: by UpdraftPlus.Com
DavidAnderson – 1.24.3

W3 Total Cache: by BoldGrid – 2.7.2
WooCommerce.com Update Manager: by Automattic – 1.0.2
WooCommerce PayPal Payments: by WooCommerce – 2.8.0
WooCommerce Shipping & Tax: by WooCommerce – 2.6.0
WooCommerce Table Rate Shipping: by WooCommerce – 3.2.1
WooCommerce UPS Shipping Plugin with Print Label: by PluginHive – 5.0.1
WP-Optimize - Clean, Compress, Cache: by David Anderson
Ruhani Rabin
Team Updraft – 3.3.2

WP All Import - WooCommerce Import Add-On Pro: by Soflyy – 4.0.0
WP All Import Pro: by Soflyy – 4.8.7
WP Overnight Sidekick: by WP Overnight – 2.5.1
Yoast SEO: by Team Yoast – 22.8

### Must Use Plugins (1) ###

simba-tfa-encryption-key.php: by  –

### Settings ###

API Enabled: –
Force SSL: –
Currency: EUR (€)
Currency Position: right_space
Thousand Separator: .
Decimal Separator: ,
Number of Decimals: 2
Taxonomies: Product Types: external (external)
grouped (grouped)
simple (simple)
variable (variable)

Taxonomies: Product Visibility: exclude-from-catalog (exclude-from-catalog)
exclude-from-search (exclude-from-search)
featured (featured)
outofstock (outofstock)
rated-1 (rated-1)
rated-2 (rated-2)
rated-3 (rated-3)
rated-4 (rated-4)
rated-5 (rated-5)

Connected to WooCommerce.com: –
Enforce Approved Product Download Directories: ✔
HPOS feature enabled: ✔
Order datastore: Automattic\WooCommerce\Internal\DataStores\Orders\OrdersTableDataStore
HPOS data sync enabled: –

### Logging ###

Enabled: ✔
Handler: Automattic\WooCommerce\Internal\Admin\Logging\LogHandlerFileV2
Retention period: 30 days
Level threshold: –
Log directory size: 1 MB

### WC Pages ###

Shop base: #7 - /shop/
Cart: #8 - /cart/
Checkout: #9 - /checkout/
My account: #10 - /account/
Terms and conditions: ❌ Page not set

### Theme ###

Name: Twenty Twenty-Four
Version: 1.1
Author URL: https://wordpress.org
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: /var/www/html/web/app/plugins/woocommerce/templates/block-notices/error.php
/var/www/html/web/app/plugins/woocommerce/templates/block-notices/notice.php
/var/www/html/web/app/plugins/woocommerce/templates/block-notices/success.php


### Admin ###

Enabled Features: activity-panels
analytics
product-block-editor
coupons
core-profiler
customize-store
customer-effort-score-tracks
import-products-task
experimental-fashion-sample-products
shipping-smart-defaults
shipping-setting-tour
homescreen
marketing
mobile-app-banner
navigation
onboarding
onboarding-tasks
product-variation-management
product-virtual-downloadable
product-external-affiliate
product-grouped
product-linked
product-pre-publish-modal
product-custom-fields
remote-inbox-notifications
remote-free-extensions
payment-gateway-suggestions
shipping-label-banner
subscriptions
store-alerts
transient-notices
woo-mobile-welcome
wc-pay-promotion
wc-pay-welcome-page

Disabled Features: minified-js
new-product-management-experience
settings
async-product-editor-category-field
launch-your-store

Daily Cron: ✔ Next scheduled: 2024-06-15 10:07:20 +00:00
Options: ✔
Notes: 64
Onboarding: completed

### Action Scheduler ###

Complete: 3,930
Oldest: 2024-06-13 10:07:31 +0000
Newest: 2024-06-14 13:35:20 +0000

Failed: 3
Oldest: 2024-06-13 10:30:21 +0000
Newest: 2024-06-14 13:29:20 +0000

Pending: 4
Oldest: 2024-06-14 22:39:54 +0000
Newest: 2024-06-15 10:55:00 +0000


### CoCart ###

Version: 4.1.0
Database Version: 4.1.0
Install Date: June 13
2024

Carts in Session: 1
Carts Active: 1 out of 1 in session.
Carts Expiring Soon: 0 out of 1 in session.
Carts Expired: 0 out of 1 in session.
Carts Source (by CoCart): 1
Carts Source (by Web): 0
Carts Source (by Other): 0

### Status report information ###

Generated at: 2024-06-14 13:38:40 +00:00
```
</details>

**Comment by seb86** [comment]
@jnz31 Thanks for reporting the bug. A patch will be out soon.

**Comment by jnz31** [comment]
@seb86 thanks! almost, you created a new bug by removing
`$attachment_sizes    = apply_filters( 'cocart_products_image_sizes', array_merge( get_intermediate_image_sizes(), array( 'full', 'custom' ) ) );`

the bug:
Warning:  Undefined variable $attachment_sizes in /var/www/html/web/app/plugins/cart-rest-api-for-woocommerce/includes/api/cocart/v2/products/class-cocart-products-controller.php on line 271

**Comment by seb86** [comment]
@jnz31 Shit. Sorry bro. I thought I stashed other changes away before committing the file. I blame patching on the last day of the week. 😓 Will get this fixed later today.

**Comment by seb86** [comment]
@jnz31 Reverted the line removed and did a backport release. Just re-download v4.1.1 and you should be good.
